import json
import os
from datetime import datetime

def generate_paper(
    run_output_dir: str,
    config: dict,
    sr_result: dict,
    kg: dict,
    metrics: dict
) -> str:
    """
    Generates a markdown paper summarizing the experiment.
    """
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    mode = config.get('mode', 'physics')
    
    markdown = f"""# Automated Scientific Discovery Report
**Date:** {timestamp}
**Mode:** {mode}
**Task:** {config.get('task')}

## Abstract
This report documents the automated discovery of the target system's mechanism.
"""

    def format_metric(val, fmt):
        if val is None or not isinstance(val, (int, float)):
            return "N/A"
        return f"{val:{fmt}}"

    if mode == 'physics':
        markdown += f"""
## 1. Methodology (Physics)
### 1.1 Data Collection
We collected {config.get('n_samples')} samples. The dataset was split into training and holdout sets.

### 1.2 Symbolic Regression
We employed PySR to discover candidate equations.

## 2. Results
### 2.1 Discovered Equation
$$
{sr_result.get('equation')}
$$

**Complexity:** {sr_result.get('complexity')}
**Fit Score:** {sr_result.get('score')}

### 2.2 Performance Metrics
- **R^2 Score:** {format_metric(metrics.get('r2'), '.4f')}
- **MSE:** {format_metric(metrics.get('mse'), '.2e')}
- **RMSLE:** {format_metric(metrics.get('rmsle'), '.6f')}
- **Symbolic Accuracy:** {"YES (Matched Ground Truth)" if metrics.get('symbolic_match') else "NO (Structural Variation)"}
"""

    elif mode == 'causal':
        markdown += f"""
## 1. Methodology (Causal Discovery)
### 1.1 Environment
We analyzed specific interventions on {sr_result.get('nodes')} nodes.

### 1.2 Causal Inference
We used an intervention-based heuristic to uncover the DAG topology.

## 2. Results
### 2.1 Metrics (vs Ground Truth)
- **True Edges:** {metrics.get('true_edges')}
- **Predicted Edges:** {metrics.get('pred_edges')}
- **Precision:** {format_metric(metrics.get('precision'), '.4f')}
- **Recall:** {format_metric(metrics.get('recall'), '.4f')}
- **F1 Score:** {format_metric(metrics.get('f1'), '.4f')}
"""

    markdown += f"""
## 3. Knowledge Graph Analysis
The structure was parsed into a Knowledge Graph.
- **Nodes:** {len(kg.get('nodes', []))}
- **Edges:** {len(kg.get('links', kg.get('edges', [])))}

(See `kg.json` for full structure)

## 4. Conclusion
The automated system successfully recovered a candidate mechanism.
---
*Generated by Mini AI-Scientist*
"""
    
    output_path = os.path.join(run_output_dir, "paper.md")
    with open(output_path, "w") as f:
        f.write(markdown)
        
    return output_path
